// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Planetarium.Docker.Api.Migrations
{
    [DbContext(typeof(PlanetariumDbContext))]
    partial class PlanetariumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Atmosphere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DGD")
                        .HasColumnType("int");

                    b.Property<string>("DiscoveredBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscoveryYear")
                        .HasColumnType("int");

                    b.Property<double>("DistanceAU")
                        .HasColumnType("float");

                    b.Property<bool>("HasRings")
                        .HasColumnType("bit");

                    b.Property<double>("MassEarths")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanetID")
                        .HasColumnType("int");

                    b.Property<double>("RadiusKm")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("SeedState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("JsonHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SeedState");
                });
#pragma warning restore 612, 618
        }
    }
}
